### ISSUE TITLE
parrot, gamepad and face bindings gets identified as commands

### ISSUE THREAD

**Issue by AndreasArvidsson** [wenkokke/tree-sitter-talon#25] opened 2023-06-30 09:47 UTC
These lines gets identified as `command_declaration`
```
face(smile): "smile"
parrot(pop): "pop"
gamepad(north): "north"
```

**Comment by wenkokke** [comment] 2023-06-30 11:34
Yes, they're currently unsupported.

**Comment by wenkokke** [comment] 2023-08-03 12:14
Duplicate of #20 (now fixed)

**Closed as completed by wenkokke** 2023-08-03 12:14 UTC
